name: Publish branch image

on:
  push:
    tags:
      - v*

env:
  # https://github.com/features/packages
  GHCR_REGISTRY_HOST: ghcr.io
  GHCR_REGISTRY_USERNAME: ${{ secrets.PACKAGES_USER }}
  GHCR_REGISTRY_PASSWORD: ${{ secrets.PACKAGES_TOKEN }}

jobs:

  create-latest-image:
    environment: 'develop'
    name: Create branch docker image
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.4.1
        with:
          access_token: ${{ github.token }}

      -
        name: Checkout
        uses: actions/checkout@v2

      -
        # Create lowercase string
        # ${GITHUB_REF##*/} -> branch name (master / develop)
        name: Create tag image
        run: |
          echo "GHCR_IMAGE=${{ env.GHCR_REGISTRY_HOST }}/${GITHUB_REPOSITORY,,}:${GITHUB_REF##*/}" >> ${GITHUB_ENV}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.GHCR_REGISTRY_HOST }}
          username: ${{ env.GHCR_REGISTRY_USERNAME }}
          password: ${{ env.GHCR_REGISTRY_PASSWORD }}

      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: |
            ${{ env.GHCR_IMAGE }}
